/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CampaignRouteRouteImport } from './routes/campaign/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignComponentsExecutionStepRouteImport } from './routes/campaign/components/execution-step'

const CampaignRouteRoute = CampaignRouteRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignComponentsExecutionStepRoute =
  CampaignComponentsExecutionStepRouteImport.update({
    id: '/components/execution-step',
    path: '/components/execution-step',
    getParentRoute: () => CampaignRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRouteRouteWithChildren
  '/campaign/components/execution-step': typeof CampaignComponentsExecutionStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRouteRouteWithChildren
  '/campaign/components/execution-step': typeof CampaignComponentsExecutionStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRouteRouteWithChildren
  '/campaign/components/execution-step': typeof CampaignComponentsExecutionStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/campaign' | '/campaign/components/execution-step'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/campaign' | '/campaign/components/execution-step'
  id: '__root__' | '/' | '/campaign' | '/campaign/components/execution-step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignRouteRoute: typeof CampaignRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/components/execution-step': {
      id: '/campaign/components/execution-step'
      path: '/components/execution-step'
      fullPath: '/campaign/components/execution-step'
      preLoaderRoute: typeof CampaignComponentsExecutionStepRouteImport
      parentRoute: typeof CampaignRouteRoute
    }
  }
}

interface CampaignRouteRouteChildren {
  CampaignComponentsExecutionStepRoute: typeof CampaignComponentsExecutionStepRoute
}

const CampaignRouteRouteChildren: CampaignRouteRouteChildren = {
  CampaignComponentsExecutionStepRoute: CampaignComponentsExecutionStepRoute,
}

const CampaignRouteRouteWithChildren = CampaignRouteRoute._addFileChildren(
  CampaignRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignRouteRoute: CampaignRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
